name: SkyWarsPE
api: 3.0.0
version: 0.0.1
main: SkyWarsPE\SkyWarsPE
author: PlexOfDevs
description: SkyWarsPE Minigame Plugin
website: https://github.com/PlexOfDevs/SkyWarsPE

permissions:
  sw.cmd:
    description: Permission to all SkyWarsPE commands
    default: op
    children:
      sw.cmd.help:
        description: Permission for /sw help
        default: op
      sw.cmd.create:
        description: Permission for /sw create
        default: op
      sw.cmd.remove:
        description: Permission for /sw remove
        default: op
      sw.cmd.set:
        description: Permission for /sw set
        default: op
      sw.cmd.arenas:
        description: Permission for /sw arenas
        default: op
